// Code generated by protoc-gen-go. DO NOT EDIT.
// source: headers/headers.proto

package headers

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestHeaders struct {
	Headers              []*RequestHeader `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RequestHeaders) Reset()         { *m = RequestHeaders{} }
func (m *RequestHeaders) String() string { return proto.CompactTextString(m) }
func (*RequestHeaders) ProtoMessage()    {}
func (*RequestHeaders) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6c6a505b179efb9, []int{0}
}

func (m *RequestHeaders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestHeaders.Unmarshal(m, b)
}
func (m *RequestHeaders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestHeaders.Marshal(b, m, deterministic)
}
func (m *RequestHeaders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestHeaders.Merge(m, src)
}
func (m *RequestHeaders) XXX_Size() int {
	return xxx_messageInfo_RequestHeaders.Size(m)
}
func (m *RequestHeaders) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestHeaders.DiscardUnknown(m)
}

var xxx_messageInfo_RequestHeaders proto.InternalMessageInfo

func (m *RequestHeaders) GetHeaders() []*RequestHeader {
	if m != nil {
		return m.Headers
	}
	return nil
}

type RequestHeader struct {
	PartitionId          uint32   `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	Index                uint64   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestHeader) Reset()         { *m = RequestHeader{} }
func (m *RequestHeader) String() string { return proto.CompactTextString(m) }
func (*RequestHeader) ProtoMessage()    {}
func (*RequestHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6c6a505b179efb9, []int{1}
}

func (m *RequestHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestHeader.Unmarshal(m, b)
}
func (m *RequestHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestHeader.Marshal(b, m, deterministic)
}
func (m *RequestHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestHeader.Merge(m, src)
}
func (m *RequestHeader) XXX_Size() int {
	return xxx_messageInfo_RequestHeader.Size(m)
}
func (m *RequestHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestHeader.DiscardUnknown(m)
}

var xxx_messageInfo_RequestHeader proto.InternalMessageInfo

func (m *RequestHeader) GetPartitionId() uint32 {
	if m != nil {
		return m.PartitionId
	}
	return 0
}

func (m *RequestHeader) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

type ResponseHeaders struct {
	Headers              []*ResponseHeader `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ResponseHeaders) Reset()         { *m = ResponseHeaders{} }
func (m *ResponseHeaders) String() string { return proto.CompactTextString(m) }
func (*ResponseHeaders) ProtoMessage()    {}
func (*ResponseHeaders) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6c6a505b179efb9, []int{2}
}

func (m *ResponseHeaders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseHeaders.Unmarshal(m, b)
}
func (m *ResponseHeaders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseHeaders.Marshal(b, m, deterministic)
}
func (m *ResponseHeaders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseHeaders.Merge(m, src)
}
func (m *ResponseHeaders) XXX_Size() int {
	return xxx_messageInfo_ResponseHeaders.Size(m)
}
func (m *ResponseHeaders) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseHeaders.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseHeaders proto.InternalMessageInfo

func (m *ResponseHeaders) GetHeaders() []*ResponseHeader {
	if m != nil {
		return m.Headers
	}
	return nil
}

type ResponseHeader struct {
	PartitionId          uint32   `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	Index                uint64   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseHeader) Reset()         { *m = ResponseHeader{} }
func (m *ResponseHeader) String() string { return proto.CompactTextString(m) }
func (*ResponseHeader) ProtoMessage()    {}
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6c6a505b179efb9, []int{3}
}

func (m *ResponseHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseHeader.Unmarshal(m, b)
}
func (m *ResponseHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseHeader.Marshal(b, m, deterministic)
}
func (m *ResponseHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseHeader.Merge(m, src)
}
func (m *ResponseHeader) XXX_Size() int {
	return xxx_messageInfo_ResponseHeader.Size(m)
}
func (m *ResponseHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseHeader proto.InternalMessageInfo

func (m *ResponseHeader) GetPartitionId() uint32 {
	if m != nil {
		return m.PartitionId
	}
	return 0
}

func (m *ResponseHeader) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

type SessionHeaders struct {
	SessionId            uint64           `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Headers              []*SessionHeader `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SessionHeaders) Reset()         { *m = SessionHeaders{} }
func (m *SessionHeaders) String() string { return proto.CompactTextString(m) }
func (*SessionHeaders) ProtoMessage()    {}
func (*SessionHeaders) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6c6a505b179efb9, []int{4}
}

func (m *SessionHeaders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionHeaders.Unmarshal(m, b)
}
func (m *SessionHeaders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionHeaders.Marshal(b, m, deterministic)
}
func (m *SessionHeaders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionHeaders.Merge(m, src)
}
func (m *SessionHeaders) XXX_Size() int {
	return xxx_messageInfo_SessionHeaders.Size(m)
}
func (m *SessionHeaders) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionHeaders.DiscardUnknown(m)
}

var xxx_messageInfo_SessionHeaders proto.InternalMessageInfo

func (m *SessionHeaders) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *SessionHeaders) GetHeaders() []*SessionHeader {
	if m != nil {
		return m.Headers
	}
	return nil
}

type SessionHeader struct {
	PartitionId          uint32                 `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	LastSequenceNumber   uint64                 `protobuf:"varint,2,opt,name=last_sequence_number,json=lastSequenceNumber,proto3" json:"last_sequence_number,omitempty"`
	Streams              []*SessionStreamHeader `protobuf:"bytes,3,rep,name=streams,proto3" json:"streams,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SessionHeader) Reset()         { *m = SessionHeader{} }
func (m *SessionHeader) String() string { return proto.CompactTextString(m) }
func (*SessionHeader) ProtoMessage()    {}
func (*SessionHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6c6a505b179efb9, []int{5}
}

func (m *SessionHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionHeader.Unmarshal(m, b)
}
func (m *SessionHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionHeader.Marshal(b, m, deterministic)
}
func (m *SessionHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionHeader.Merge(m, src)
}
func (m *SessionHeader) XXX_Size() int {
	return xxx_messageInfo_SessionHeader.Size(m)
}
func (m *SessionHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionHeader.DiscardUnknown(m)
}

var xxx_messageInfo_SessionHeader proto.InternalMessageInfo

func (m *SessionHeader) GetPartitionId() uint32 {
	if m != nil {
		return m.PartitionId
	}
	return 0
}

func (m *SessionHeader) GetLastSequenceNumber() uint64 {
	if m != nil {
		return m.LastSequenceNumber
	}
	return 0
}

func (m *SessionHeader) GetStreams() []*SessionStreamHeader {
	if m != nil {
		return m.Streams
	}
	return nil
}

type SessionCommandHeaders struct {
	SessionId            uint64                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Headers              []*SessionCommandHeader `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *SessionCommandHeaders) Reset()         { *m = SessionCommandHeaders{} }
func (m *SessionCommandHeaders) String() string { return proto.CompactTextString(m) }
func (*SessionCommandHeaders) ProtoMessage()    {}
func (*SessionCommandHeaders) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6c6a505b179efb9, []int{6}
}

func (m *SessionCommandHeaders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionCommandHeaders.Unmarshal(m, b)
}
func (m *SessionCommandHeaders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionCommandHeaders.Marshal(b, m, deterministic)
}
func (m *SessionCommandHeaders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionCommandHeaders.Merge(m, src)
}
func (m *SessionCommandHeaders) XXX_Size() int {
	return xxx_messageInfo_SessionCommandHeaders.Size(m)
}
func (m *SessionCommandHeaders) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionCommandHeaders.DiscardUnknown(m)
}

var xxx_messageInfo_SessionCommandHeaders proto.InternalMessageInfo

func (m *SessionCommandHeaders) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *SessionCommandHeaders) GetHeaders() []*SessionCommandHeader {
	if m != nil {
		return m.Headers
	}
	return nil
}

type SessionCommandHeader struct {
	PartitionId          uint32   `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	SequenceNumber       uint64   `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionCommandHeader) Reset()         { *m = SessionCommandHeader{} }
func (m *SessionCommandHeader) String() string { return proto.CompactTextString(m) }
func (*SessionCommandHeader) ProtoMessage()    {}
func (*SessionCommandHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6c6a505b179efb9, []int{7}
}

func (m *SessionCommandHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionCommandHeader.Unmarshal(m, b)
}
func (m *SessionCommandHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionCommandHeader.Marshal(b, m, deterministic)
}
func (m *SessionCommandHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionCommandHeader.Merge(m, src)
}
func (m *SessionCommandHeader) XXX_Size() int {
	return xxx_messageInfo_SessionCommandHeader.Size(m)
}
func (m *SessionCommandHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionCommandHeader.DiscardUnknown(m)
}

var xxx_messageInfo_SessionCommandHeader proto.InternalMessageInfo

func (m *SessionCommandHeader) GetPartitionId() uint32 {
	if m != nil {
		return m.PartitionId
	}
	return 0
}

func (m *SessionCommandHeader) GetSequenceNumber() uint64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

type SessionQueryHeaders struct {
	SessionId            uint64                `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Headers              []*SessionQueryHeader `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SessionQueryHeaders) Reset()         { *m = SessionQueryHeaders{} }
func (m *SessionQueryHeaders) String() string { return proto.CompactTextString(m) }
func (*SessionQueryHeaders) ProtoMessage()    {}
func (*SessionQueryHeaders) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6c6a505b179efb9, []int{8}
}

func (m *SessionQueryHeaders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionQueryHeaders.Unmarshal(m, b)
}
func (m *SessionQueryHeaders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionQueryHeaders.Marshal(b, m, deterministic)
}
func (m *SessionQueryHeaders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionQueryHeaders.Merge(m, src)
}
func (m *SessionQueryHeaders) XXX_Size() int {
	return xxx_messageInfo_SessionQueryHeaders.Size(m)
}
func (m *SessionQueryHeaders) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionQueryHeaders.DiscardUnknown(m)
}

var xxx_messageInfo_SessionQueryHeaders proto.InternalMessageInfo

func (m *SessionQueryHeaders) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *SessionQueryHeaders) GetHeaders() []*SessionQueryHeader {
	if m != nil {
		return m.Headers
	}
	return nil
}

type SessionQueryHeader struct {
	PartitionId          uint32   `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	LastIndex            uint64   `protobuf:"varint,2,opt,name=last_index,json=lastIndex,proto3" json:"last_index,omitempty"`
	LastSequenceNumber   uint64   `protobuf:"varint,3,opt,name=last_sequence_number,json=lastSequenceNumber,proto3" json:"last_sequence_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionQueryHeader) Reset()         { *m = SessionQueryHeader{} }
func (m *SessionQueryHeader) String() string { return proto.CompactTextString(m) }
func (*SessionQueryHeader) ProtoMessage()    {}
func (*SessionQueryHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6c6a505b179efb9, []int{9}
}

func (m *SessionQueryHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionQueryHeader.Unmarshal(m, b)
}
func (m *SessionQueryHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionQueryHeader.Marshal(b, m, deterministic)
}
func (m *SessionQueryHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionQueryHeader.Merge(m, src)
}
func (m *SessionQueryHeader) XXX_Size() int {
	return xxx_messageInfo_SessionQueryHeader.Size(m)
}
func (m *SessionQueryHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionQueryHeader.DiscardUnknown(m)
}

var xxx_messageInfo_SessionQueryHeader proto.InternalMessageInfo

func (m *SessionQueryHeader) GetPartitionId() uint32 {
	if m != nil {
		return m.PartitionId
	}
	return 0
}

func (m *SessionQueryHeader) GetLastIndex() uint64 {
	if m != nil {
		return m.LastIndex
	}
	return 0
}

func (m *SessionQueryHeader) GetLastSequenceNumber() uint64 {
	if m != nil {
		return m.LastSequenceNumber
	}
	return 0
}

type SessionResponseHeaders struct {
	SessionId            uint64                   `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Headers              []*SessionResponseHeader `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *SessionResponseHeaders) Reset()         { *m = SessionResponseHeaders{} }
func (m *SessionResponseHeaders) String() string { return proto.CompactTextString(m) }
func (*SessionResponseHeaders) ProtoMessage()    {}
func (*SessionResponseHeaders) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6c6a505b179efb9, []int{10}
}

func (m *SessionResponseHeaders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionResponseHeaders.Unmarshal(m, b)
}
func (m *SessionResponseHeaders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionResponseHeaders.Marshal(b, m, deterministic)
}
func (m *SessionResponseHeaders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionResponseHeaders.Merge(m, src)
}
func (m *SessionResponseHeaders) XXX_Size() int {
	return xxx_messageInfo_SessionResponseHeaders.Size(m)
}
func (m *SessionResponseHeaders) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionResponseHeaders.DiscardUnknown(m)
}

var xxx_messageInfo_SessionResponseHeaders proto.InternalMessageInfo

func (m *SessionResponseHeaders) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *SessionResponseHeaders) GetHeaders() []*SessionResponseHeader {
	if m != nil {
		return m.Headers
	}
	return nil
}

type SessionResponseHeader struct {
	PartitionId          uint32                 `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	Index                uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	SequenceNumber       uint64                 `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Streams              []*SessionStreamHeader `protobuf:"bytes,4,rep,name=streams,proto3" json:"streams,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SessionResponseHeader) Reset()         { *m = SessionResponseHeader{} }
func (m *SessionResponseHeader) String() string { return proto.CompactTextString(m) }
func (*SessionResponseHeader) ProtoMessage()    {}
func (*SessionResponseHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6c6a505b179efb9, []int{11}
}

func (m *SessionResponseHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionResponseHeader.Unmarshal(m, b)
}
func (m *SessionResponseHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionResponseHeader.Marshal(b, m, deterministic)
}
func (m *SessionResponseHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionResponseHeader.Merge(m, src)
}
func (m *SessionResponseHeader) XXX_Size() int {
	return xxx_messageInfo_SessionResponseHeader.Size(m)
}
func (m *SessionResponseHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionResponseHeader.DiscardUnknown(m)
}

var xxx_messageInfo_SessionResponseHeader proto.InternalMessageInfo

func (m *SessionResponseHeader) GetPartitionId() uint32 {
	if m != nil {
		return m.PartitionId
	}
	return 0
}

func (m *SessionResponseHeader) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *SessionResponseHeader) GetSequenceNumber() uint64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *SessionResponseHeader) GetStreams() []*SessionStreamHeader {
	if m != nil {
		return m.Streams
	}
	return nil
}

type SessionStreamHeader struct {
	StreamId             uint64   `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Index                uint64   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	LastItemNumber       uint64   `protobuf:"varint,3,opt,name=last_item_number,json=lastItemNumber,proto3" json:"last_item_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionStreamHeader) Reset()         { *m = SessionStreamHeader{} }
func (m *SessionStreamHeader) String() string { return proto.CompactTextString(m) }
func (*SessionStreamHeader) ProtoMessage()    {}
func (*SessionStreamHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6c6a505b179efb9, []int{12}
}

func (m *SessionStreamHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionStreamHeader.Unmarshal(m, b)
}
func (m *SessionStreamHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionStreamHeader.Marshal(b, m, deterministic)
}
func (m *SessionStreamHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionStreamHeader.Merge(m, src)
}
func (m *SessionStreamHeader) XXX_Size() int {
	return xxx_messageInfo_SessionStreamHeader.Size(m)
}
func (m *SessionStreamHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionStreamHeader.DiscardUnknown(m)
}

var xxx_messageInfo_SessionStreamHeader proto.InternalMessageInfo

func (m *SessionStreamHeader) GetStreamId() uint64 {
	if m != nil {
		return m.StreamId
	}
	return 0
}

func (m *SessionStreamHeader) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *SessionStreamHeader) GetLastItemNumber() uint64 {
	if m != nil {
		return m.LastItemNumber
	}
	return 0
}

func init() {
	proto.RegisterType((*RequestHeaders)(nil), "atomix.headers.RequestHeaders")
	proto.RegisterType((*RequestHeader)(nil), "atomix.headers.RequestHeader")
	proto.RegisterType((*ResponseHeaders)(nil), "atomix.headers.ResponseHeaders")
	proto.RegisterType((*ResponseHeader)(nil), "atomix.headers.ResponseHeader")
	proto.RegisterType((*SessionHeaders)(nil), "atomix.headers.SessionHeaders")
	proto.RegisterType((*SessionHeader)(nil), "atomix.headers.SessionHeader")
	proto.RegisterType((*SessionCommandHeaders)(nil), "atomix.headers.SessionCommandHeaders")
	proto.RegisterType((*SessionCommandHeader)(nil), "atomix.headers.SessionCommandHeader")
	proto.RegisterType((*SessionQueryHeaders)(nil), "atomix.headers.SessionQueryHeaders")
	proto.RegisterType((*SessionQueryHeader)(nil), "atomix.headers.SessionQueryHeader")
	proto.RegisterType((*SessionResponseHeaders)(nil), "atomix.headers.SessionResponseHeaders")
	proto.RegisterType((*SessionResponseHeader)(nil), "atomix.headers.SessionResponseHeader")
	proto.RegisterType((*SessionStreamHeader)(nil), "atomix.headers.SessionStreamHeader")
}

func init() { proto.RegisterFile("headers/headers.proto", fileDescriptor_a6c6a505b179efb9) }

var fileDescriptor_a6c6a505b179efb9 = []byte{
	// 463 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xdd, 0x8e, 0xd2, 0x40,
	0x14, 0xc7, 0x33, 0x14, 0x45, 0x0e, 0x52, 0xcc, 0x08, 0xa4, 0xd1, 0x60, 0xb0, 0x6a, 0xec, 0x55,
	0x35, 0x7a, 0xa1, 0x17, 0x7e, 0x24, 0x7a, 0x43, 0x63, 0x62, 0xb4, 0x3c, 0x00, 0x29, 0x74, 0xb2,
	0x34, 0xd9, 0x76, 0xba, 0x33, 0xc3, 0x86, 0x7d, 0x83, 0x7d, 0x8f, 0x7d, 0x89, 0x7d, 0xbc, 0x4d,
	0xdb, 0x29, 0xfd, 0xa0, 0x93, 0x6d, 0xc8, 0x5e, 0x11, 0xce, 0x7f, 0xe6, 0xcc, 0xef, 0xfc, 0xcf,
	0x39, 0x85, 0xc9, 0x96, 0x78, 0x3e, 0x61, 0xfc, 0x83, 0xfc, 0xb5, 0x63, 0x46, 0x05, 0xc5, 0xba,
	0x27, 0x68, 0x18, 0xec, 0x6d, 0x19, 0x35, 0x1d, 0xd0, 0x5d, 0x72, 0xb1, 0x23, 0x5c, 0x2c, 0xb2,
	0x08, 0xfe, 0x02, 0x3d, 0x29, 0x1a, 0x68, 0xae, 0x59, 0x83, 0x4f, 0x33, 0xbb, 0x7a, 0xc7, 0xae,
	0x5c, 0x70, 0xf3, 0xd3, 0xe6, 0x02, 0x86, 0x15, 0x05, 0xbf, 0x86, 0xa7, 0xb1, 0xc7, 0x44, 0x20,
	0x02, 0x1a, 0xad, 0x02, 0xdf, 0x40, 0x73, 0x64, 0x0d, 0xdd, 0xc1, 0x21, 0xe6, 0xf8, 0x78, 0x0c,
	0x8f, 0x82, 0xc8, 0x27, 0x7b, 0xa3, 0x33, 0x47, 0x56, 0xd7, 0xcd, 0xfe, 0x98, 0x7f, 0x60, 0xe4,
	0x12, 0x1e, 0xd3, 0x88, 0x93, 0x9c, 0xea, 0x6b, 0x9d, 0xea, 0xd5, 0x31, 0x55, 0xf9, 0x46, 0x81,
	0x95, 0x56, 0x58, 0x96, 0x4e, 0xe7, 0xda, 0x82, 0xbe, 0x24, 0x9c, 0x07, 0x34, 0xca, 0xb1, 0x66,
	0x00, 0x3c, 0x8b, 0xe4, 0x89, 0xba, 0x6e, 0x5f, 0x46, 0x1c, 0xbf, 0xec, 0x65, 0xa7, 0xd9, 0xcb,
	0x4a, 0xbe, 0x02, 0xfa, 0x06, 0xc1, 0xb0, 0x22, 0xb5, 0x81, 0xfe, 0x08, 0xe3, 0x73, 0x8f, 0x8b,
	0x15, 0x4f, 0xba, 0x10, 0x6d, 0xc8, 0x2a, 0xda, 0x85, 0x6b, 0xc2, 0x64, 0x0d, 0x38, 0xd1, 0x96,
	0x52, 0xfa, 0x9b, 0x2a, 0xf8, 0x3b, 0xf4, 0xb8, 0x60, 0xc4, 0x0b, 0xb9, 0xa1, 0xa5, 0x7c, 0x6f,
	0x14, 0x7c, 0xcb, 0xf4, 0x54, 0x4e, 0x29, 0xef, 0x98, 0x97, 0x30, 0x91, 0xfa, 0x6f, 0x1a, 0x86,
	0x5e, 0xe4, 0xb7, 0xb4, 0xe5, 0x47, 0xdd, 0x96, 0xb7, 0x8a, 0x67, 0x2b, 0x69, 0x0b, 0x77, 0xd6,
	0x30, 0x6e, 0x3a, 0xd0, 0xc6, 0xa3, 0xf7, 0x30, 0x6a, 0xb6, 0x47, 0xe7, 0x15, 0x6b, 0x4c, 0x06,
	0xcf, 0xe5, 0x1b, 0xff, 0x77, 0x84, 0x5d, 0xb5, 0xac, 0xec, 0x5b, 0xbd, 0x32, 0x53, 0x51, 0x59,
	0x29, 0x69, 0x51, 0xd7, 0x35, 0x02, 0x7c, 0xac, 0xb7, 0x29, 0x6b, 0x06, 0x90, 0xb6, 0xbe, 0x3c,
	0xb4, 0xfd, 0x24, 0xe2, 0x24, 0x01, 0xe5, 0x64, 0x68, 0xaa, 0xc9, 0x30, 0xf7, 0x30, 0x95, 0x24,
	0xf5, 0x4d, 0xbc, 0xc7, 0x81, 0x9f, 0x75, 0x07, 0xde, 0x29, 0x1c, 0x50, 0xed, 0xeb, 0x2d, 0x3a,
	0x4c, 0xd5, 0x03, 0xed, 0x6d, 0x53, 0xd3, 0xb5, 0xa6, 0xa6, 0x97, 0xf7, 0xa1, 0x7b, 0xc2, 0x3e,
	0x14, 0x33, 0x53, 0xd6, 0xf1, 0x4b, 0xe8, 0x67, 0x27, 0x0a, 0xc3, 0x9e, 0x64, 0x01, 0x25, 0xb1,
	0x05, 0xcf, 0xb2, 0x7e, 0x0a, 0x12, 0xd6, 0x90, 0xd3, 0xae, 0x0a, 0x12, 0x66, 0xc8, 0xbf, 0x5e,
	0xc0, 0x34, 0xa0, 0x39, 0xe5, 0x19, 0x8b, 0x37, 0x39, 0xea, 0x3f, 0xb4, 0x7e, 0x9c, 0x7e, 0xf3,
	0x3f, 0xdf, 0x05, 0x00, 0x00, 0xff, 0xff, 0x75, 0x83, 0xcf, 0x54, 0x0c, 0x06, 0x00, 0x00,
}
