// Code generated by protoc-gen-go. DO NOT EDIT.
// source: atomix/primitive/primitive.proto

package primitive

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Namespaced primitive name
type Name struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Name) Reset()         { *m = Name{} }
func (m *Name) String() string { return proto.CompactTextString(m) }
func (*Name) ProtoMessage()    {}
func (*Name) Descriptor() ([]byte, []int) {
	return fileDescriptor_056a91a3aedc7ac7, []int{0}
}

func (m *Name) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Name.Unmarshal(m, b)
}
func (m *Name) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Name.Marshal(b, m, deterministic)
}
func (m *Name) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Name.Merge(m, src)
}
func (m *Name) XXX_Size() int {
	return xxx_messageInfo_Name.Size(m)
}
func (m *Name) XXX_DiscardUnknown() {
	xxx_messageInfo_Name.DiscardUnknown(m)
}

var xxx_messageInfo_Name proto.InternalMessageInfo

func (m *Name) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Name) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type GetPrimitivesRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPrimitivesRequest) Reset()         { *m = GetPrimitivesRequest{} }
func (m *GetPrimitivesRequest) String() string { return proto.CompactTextString(m) }
func (*GetPrimitivesRequest) ProtoMessage()    {}
func (*GetPrimitivesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_056a91a3aedc7ac7, []int{1}
}

func (m *GetPrimitivesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPrimitivesRequest.Unmarshal(m, b)
}
func (m *GetPrimitivesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPrimitivesRequest.Marshal(b, m, deterministic)
}
func (m *GetPrimitivesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPrimitivesRequest.Merge(m, src)
}
func (m *GetPrimitivesRequest) XXX_Size() int {
	return xxx_messageInfo_GetPrimitivesRequest.Size(m)
}
func (m *GetPrimitivesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPrimitivesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPrimitivesRequest proto.InternalMessageInfo

func (m *GetPrimitivesRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type GetPrimitivesResponse struct {
	Primitives           []*PrimitiveInfo `protobuf:"bytes,1,rep,name=primitives,proto3" json:"primitives,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetPrimitivesResponse) Reset()         { *m = GetPrimitivesResponse{} }
func (m *GetPrimitivesResponse) String() string { return proto.CompactTextString(m) }
func (*GetPrimitivesResponse) ProtoMessage()    {}
func (*GetPrimitivesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_056a91a3aedc7ac7, []int{2}
}

func (m *GetPrimitivesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPrimitivesResponse.Unmarshal(m, b)
}
func (m *GetPrimitivesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPrimitivesResponse.Marshal(b, m, deterministic)
}
func (m *GetPrimitivesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPrimitivesResponse.Merge(m, src)
}
func (m *GetPrimitivesResponse) XXX_Size() int {
	return xxx_messageInfo_GetPrimitivesResponse.Size(m)
}
func (m *GetPrimitivesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPrimitivesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPrimitivesResponse proto.InternalMessageInfo

func (m *GetPrimitivesResponse) GetPrimitives() []*PrimitiveInfo {
	if m != nil {
		return m.Primitives
	}
	return nil
}

type PrimitiveInfo struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name                 *Name    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimitiveInfo) Reset()         { *m = PrimitiveInfo{} }
func (m *PrimitiveInfo) String() string { return proto.CompactTextString(m) }
func (*PrimitiveInfo) ProtoMessage()    {}
func (*PrimitiveInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_056a91a3aedc7ac7, []int{3}
}

func (m *PrimitiveInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimitiveInfo.Unmarshal(m, b)
}
func (m *PrimitiveInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimitiveInfo.Marshal(b, m, deterministic)
}
func (m *PrimitiveInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimitiveInfo.Merge(m, src)
}
func (m *PrimitiveInfo) XXX_Size() int {
	return xxx_messageInfo_PrimitiveInfo.Size(m)
}
func (m *PrimitiveInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimitiveInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PrimitiveInfo proto.InternalMessageInfo

func (m *PrimitiveInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PrimitiveInfo) GetName() *Name {
	if m != nil {
		return m.Name
	}
	return nil
}

func init() {
	proto.RegisterType((*Name)(nil), "atomix.primitive.Name")
	proto.RegisterType((*GetPrimitivesRequest)(nil), "atomix.primitive.GetPrimitivesRequest")
	proto.RegisterType((*GetPrimitivesResponse)(nil), "atomix.primitive.GetPrimitivesResponse")
	proto.RegisterType((*PrimitiveInfo)(nil), "atomix.primitive.PrimitiveInfo")
}

func init() { proto.RegisterFile("atomix/primitive/primitive.proto", fileDescriptor_056a91a3aedc7ac7) }

var fileDescriptor_056a91a3aedc7ac7 = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x48, 0x2c, 0xc9, 0xcf,
	0xcd, 0xac, 0xd0, 0x2f, 0x28, 0xca, 0xcc, 0xcd, 0x2c, 0xc9, 0x2c, 0x4b, 0x45, 0xb0, 0xf4, 0x0a,
	0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x04, 0x20, 0x2a, 0xf4, 0xe0, 0xe2, 0x4a, 0x16, 0x5c, 0x2c, 0x7e,
	0x89, 0xb9, 0xa9, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a,
	0x9c, 0x41, 0x60, 0xb6, 0x90, 0x0c, 0x17, 0x27, 0x88, 0x2e, 0x2e, 0x48, 0x4c, 0x4e, 0x95, 0x60,
	0x02, 0x4b, 0x20, 0x04, 0x94, 0xb4, 0xb8, 0x44, 0xdc, 0x53, 0x4b, 0x02, 0x60, 0x26, 0x15, 0x07,
	0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x80, 0x4c, 0x2a, 0xa9, 0x2c, 0x80, 0x9b, 0x04, 0x62, 0x2b,
	0x45, 0x70, 0x89, 0xa2, 0xa9, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0xb2, 0xe7, 0xe2, 0x82,
	0xbb, 0xa5, 0x58, 0x82, 0x51, 0x81, 0x59, 0x83, 0xdb, 0x48, 0x5e, 0x0f, 0xdd, 0x95, 0x7a, 0x70,
	0x9d, 0x9e, 0x79, 0x69, 0xf9, 0x41, 0x48, 0x5a, 0x94, 0xfc, 0xb9, 0x78, 0x51, 0x24, 0xb1, 0x59,
	0x2f, 0xa4, 0x05, 0xf5, 0x1c, 0xc8, 0x0f, 0xdc, 0x46, 0x62, 0x98, 0xe6, 0x83, 0x82, 0x00, 0xe2,
	0x69, 0xa3, 0x32, 0x2e, 0x01, 0xb8, 0x81, 0xc1, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9, 0x42, 0x49,
	0x5c, 0xbc, 0x28, 0xce, 0x17, 0x52, 0xc3, 0x34, 0x02, 0x5b, 0x58, 0x48, 0xa9, 0x13, 0x54, 0x07,
	0x09, 0x07, 0x25, 0x86, 0x24, 0x36, 0x70, 0x0c, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x39,
	0x65, 0x8d, 0xd0, 0xc5, 0x01, 0x00, 0x00,
}
