// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lock/lock.proto

package lock

import (
	context "context"
	fmt "fmt"
	headers "github.com/atomix/atomix-go/proto/headers"
	protocol "github.com/atomix/atomix-go/proto/protocol"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Lock ID
type LockId struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Proto:
	//	*LockId_Raft
	//	*LockId_MultiPrimary
	//	*LockId_Log
	Proto                isLockId_Proto `protobuf_oneof:"proto"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *LockId) Reset()         { *m = LockId{} }
func (m *LockId) String() string { return proto.CompactTextString(m) }
func (*LockId) ProtoMessage()    {}
func (*LockId) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebe517841b49c3eb, []int{0}
}

func (m *LockId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockId.Unmarshal(m, b)
}
func (m *LockId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockId.Marshal(b, m, deterministic)
}
func (m *LockId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockId.Merge(m, src)
}
func (m *LockId) XXX_Size() int {
	return xxx_messageInfo_LockId.Size(m)
}
func (m *LockId) XXX_DiscardUnknown() {
	xxx_messageInfo_LockId.DiscardUnknown(m)
}

var xxx_messageInfo_LockId proto.InternalMessageInfo

func (m *LockId) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type isLockId_Proto interface {
	isLockId_Proto()
}

type LockId_Raft struct {
	Raft *protocol.MultiRaftProtocol `protobuf:"bytes,2,opt,name=raft,proto3,oneof"`
}

type LockId_MultiPrimary struct {
	MultiPrimary *protocol.MultiPrimaryProtocol `protobuf:"bytes,3,opt,name=multi_primary,json=multiPrimary,proto3,oneof"`
}

type LockId_Log struct {
	Log *protocol.DistributedLogProtocol `protobuf:"bytes,4,opt,name=log,proto3,oneof"`
}

func (*LockId_Raft) isLockId_Proto() {}

func (*LockId_MultiPrimary) isLockId_Proto() {}

func (*LockId_Log) isLockId_Proto() {}

func (m *LockId) GetProto() isLockId_Proto {
	if m != nil {
		return m.Proto
	}
	return nil
}

func (m *LockId) GetRaft() *protocol.MultiRaftProtocol {
	if x, ok := m.GetProto().(*LockId_Raft); ok {
		return x.Raft
	}
	return nil
}

func (m *LockId) GetMultiPrimary() *protocol.MultiPrimaryProtocol {
	if x, ok := m.GetProto().(*LockId_MultiPrimary); ok {
		return x.MultiPrimary
	}
	return nil
}

func (m *LockId) GetLog() *protocol.DistributedLogProtocol {
	if x, ok := m.GetProto().(*LockId_Log); ok {
		return x.Log
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*LockId) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*LockId_Raft)(nil),
		(*LockId_MultiPrimary)(nil),
		(*LockId_Log)(nil),
	}
}

type CreateRequest struct {
	Id                   *LockId            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timeout              *duration.Duration `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebe517841b49c3eb, []int{1}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetId() *LockId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *CreateRequest) GetTimeout() *duration.Duration {
	if m != nil {
		return m.Timeout
	}
	return nil
}

type CreateResponse struct {
	Headers              *headers.SessionHeaders `protobuf:"bytes,1,opt,name=headers,proto3" json:"headers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebe517841b49c3eb, []int{2}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetHeaders() *headers.SessionHeaders {
	if m != nil {
		return m.Headers
	}
	return nil
}

type KeepAliveRequest struct {
	Id                   *LockId                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Headers              *headers.SessionHeaders `protobuf:"bytes,2,opt,name=headers,proto3" json:"headers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *KeepAliveRequest) Reset()         { *m = KeepAliveRequest{} }
func (m *KeepAliveRequest) String() string { return proto.CompactTextString(m) }
func (*KeepAliveRequest) ProtoMessage()    {}
func (*KeepAliveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebe517841b49c3eb, []int{3}
}

func (m *KeepAliveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeepAliveRequest.Unmarshal(m, b)
}
func (m *KeepAliveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeepAliveRequest.Marshal(b, m, deterministic)
}
func (m *KeepAliveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeepAliveRequest.Merge(m, src)
}
func (m *KeepAliveRequest) XXX_Size() int {
	return xxx_messageInfo_KeepAliveRequest.Size(m)
}
func (m *KeepAliveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeepAliveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeepAliveRequest proto.InternalMessageInfo

func (m *KeepAliveRequest) GetId() *LockId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *KeepAliveRequest) GetHeaders() *headers.SessionHeaders {
	if m != nil {
		return m.Headers
	}
	return nil
}

type KeepAliveResponse struct {
	Headers              *headers.SessionHeaders `protobuf:"bytes,1,opt,name=headers,proto3" json:"headers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *KeepAliveResponse) Reset()         { *m = KeepAliveResponse{} }
func (m *KeepAliveResponse) String() string { return proto.CompactTextString(m) }
func (*KeepAliveResponse) ProtoMessage()    {}
func (*KeepAliveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebe517841b49c3eb, []int{4}
}

func (m *KeepAliveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeepAliveResponse.Unmarshal(m, b)
}
func (m *KeepAliveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeepAliveResponse.Marshal(b, m, deterministic)
}
func (m *KeepAliveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeepAliveResponse.Merge(m, src)
}
func (m *KeepAliveResponse) XXX_Size() int {
	return xxx_messageInfo_KeepAliveResponse.Size(m)
}
func (m *KeepAliveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KeepAliveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KeepAliveResponse proto.InternalMessageInfo

func (m *KeepAliveResponse) GetHeaders() *headers.SessionHeaders {
	if m != nil {
		return m.Headers
	}
	return nil
}

type CloseRequest struct {
	Id                   *LockId                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Headers              *headers.SessionHeaders `protobuf:"bytes,2,opt,name=headers,proto3" json:"headers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *CloseRequest) Reset()         { *m = CloseRequest{} }
func (m *CloseRequest) String() string { return proto.CompactTextString(m) }
func (*CloseRequest) ProtoMessage()    {}
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebe517841b49c3eb, []int{5}
}

func (m *CloseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseRequest.Unmarshal(m, b)
}
func (m *CloseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseRequest.Marshal(b, m, deterministic)
}
func (m *CloseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseRequest.Merge(m, src)
}
func (m *CloseRequest) XXX_Size() int {
	return xxx_messageInfo_CloseRequest.Size(m)
}
func (m *CloseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CloseRequest proto.InternalMessageInfo

func (m *CloseRequest) GetId() *LockId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *CloseRequest) GetHeaders() *headers.SessionHeaders {
	if m != nil {
		return m.Headers
	}
	return nil
}

type CloseResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseResponse) Reset()         { *m = CloseResponse{} }
func (m *CloseResponse) String() string { return proto.CompactTextString(m) }
func (*CloseResponse) ProtoMessage()    {}
func (*CloseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebe517841b49c3eb, []int{6}
}

func (m *CloseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseResponse.Unmarshal(m, b)
}
func (m *CloseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseResponse.Marshal(b, m, deterministic)
}
func (m *CloseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseResponse.Merge(m, src)
}
func (m *CloseResponse) XXX_Size() int {
	return xxx_messageInfo_CloseResponse.Size(m)
}
func (m *CloseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CloseResponse proto.InternalMessageInfo

type LockRequest struct {
	Id                   *LockId                        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Headers              *headers.SessionCommandHeaders `protobuf:"bytes,2,opt,name=headers,proto3" json:"headers,omitempty"`
	Timeout              *duration.Duration             `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *LockRequest) Reset()         { *m = LockRequest{} }
func (m *LockRequest) String() string { return proto.CompactTextString(m) }
func (*LockRequest) ProtoMessage()    {}
func (*LockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebe517841b49c3eb, []int{7}
}

func (m *LockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockRequest.Unmarshal(m, b)
}
func (m *LockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockRequest.Marshal(b, m, deterministic)
}
func (m *LockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockRequest.Merge(m, src)
}
func (m *LockRequest) XXX_Size() int {
	return xxx_messageInfo_LockRequest.Size(m)
}
func (m *LockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LockRequest proto.InternalMessageInfo

func (m *LockRequest) GetId() *LockId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *LockRequest) GetHeaders() *headers.SessionCommandHeaders {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *LockRequest) GetTimeout() *duration.Duration {
	if m != nil {
		return m.Timeout
	}
	return nil
}

type LockResponse struct {
	Headers              *headers.SessionResponseHeaders `protobuf:"bytes,1,opt,name=headers,proto3" json:"headers,omitempty"`
	Version              uint64                          `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *LockResponse) Reset()         { *m = LockResponse{} }
func (m *LockResponse) String() string { return proto.CompactTextString(m) }
func (*LockResponse) ProtoMessage()    {}
func (*LockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebe517841b49c3eb, []int{8}
}

func (m *LockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockResponse.Unmarshal(m, b)
}
func (m *LockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockResponse.Marshal(b, m, deterministic)
}
func (m *LockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockResponse.Merge(m, src)
}
func (m *LockResponse) XXX_Size() int {
	return xxx_messageInfo_LockResponse.Size(m)
}
func (m *LockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LockResponse proto.InternalMessageInfo

func (m *LockResponse) GetHeaders() *headers.SessionResponseHeaders {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *LockResponse) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

type UnlockRequest struct {
	Id                   *LockId                        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Headers              *headers.SessionCommandHeaders `protobuf:"bytes,2,opt,name=headers,proto3" json:"headers,omitempty"`
	Version              uint64                         `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *UnlockRequest) Reset()         { *m = UnlockRequest{} }
func (m *UnlockRequest) String() string { return proto.CompactTextString(m) }
func (*UnlockRequest) ProtoMessage()    {}
func (*UnlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebe517841b49c3eb, []int{9}
}

func (m *UnlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnlockRequest.Unmarshal(m, b)
}
func (m *UnlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnlockRequest.Marshal(b, m, deterministic)
}
func (m *UnlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnlockRequest.Merge(m, src)
}
func (m *UnlockRequest) XXX_Size() int {
	return xxx_messageInfo_UnlockRequest.Size(m)
}
func (m *UnlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnlockRequest proto.InternalMessageInfo

func (m *UnlockRequest) GetId() *LockId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *UnlockRequest) GetHeaders() *headers.SessionCommandHeaders {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *UnlockRequest) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

type UnlockResponse struct {
	Headers              *headers.SessionResponseHeaders `protobuf:"bytes,1,opt,name=headers,proto3" json:"headers,omitempty"`
	Unlocked             bool                            `protobuf:"varint,2,opt,name=unlocked,proto3" json:"unlocked,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *UnlockResponse) Reset()         { *m = UnlockResponse{} }
func (m *UnlockResponse) String() string { return proto.CompactTextString(m) }
func (*UnlockResponse) ProtoMessage()    {}
func (*UnlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebe517841b49c3eb, []int{10}
}

func (m *UnlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnlockResponse.Unmarshal(m, b)
}
func (m *UnlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnlockResponse.Marshal(b, m, deterministic)
}
func (m *UnlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnlockResponse.Merge(m, src)
}
func (m *UnlockResponse) XXX_Size() int {
	return xxx_messageInfo_UnlockResponse.Size(m)
}
func (m *UnlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnlockResponse proto.InternalMessageInfo

func (m *UnlockResponse) GetHeaders() *headers.SessionResponseHeaders {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *UnlockResponse) GetUnlocked() bool {
	if m != nil {
		return m.Unlocked
	}
	return false
}

type IsLockedRequest struct {
	Id                   *LockId                      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Headers              *headers.SessionQueryHeaders `protobuf:"bytes,2,opt,name=headers,proto3" json:"headers,omitempty"`
	Version              uint64                       `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *IsLockedRequest) Reset()         { *m = IsLockedRequest{} }
func (m *IsLockedRequest) String() string { return proto.CompactTextString(m) }
func (*IsLockedRequest) ProtoMessage()    {}
func (*IsLockedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebe517841b49c3eb, []int{11}
}

func (m *IsLockedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsLockedRequest.Unmarshal(m, b)
}
func (m *IsLockedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsLockedRequest.Marshal(b, m, deterministic)
}
func (m *IsLockedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsLockedRequest.Merge(m, src)
}
func (m *IsLockedRequest) XXX_Size() int {
	return xxx_messageInfo_IsLockedRequest.Size(m)
}
func (m *IsLockedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IsLockedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IsLockedRequest proto.InternalMessageInfo

func (m *IsLockedRequest) GetId() *LockId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *IsLockedRequest) GetHeaders() *headers.SessionQueryHeaders {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *IsLockedRequest) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

type IsLockedResponse struct {
	Headers              *headers.SessionResponseHeaders `protobuf:"bytes,1,opt,name=headers,proto3" json:"headers,omitempty"`
	IsLocked             bool                            `protobuf:"varint,2,opt,name=isLocked,proto3" json:"isLocked,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *IsLockedResponse) Reset()         { *m = IsLockedResponse{} }
func (m *IsLockedResponse) String() string { return proto.CompactTextString(m) }
func (*IsLockedResponse) ProtoMessage()    {}
func (*IsLockedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebe517841b49c3eb, []int{12}
}

func (m *IsLockedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsLockedResponse.Unmarshal(m, b)
}
func (m *IsLockedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsLockedResponse.Marshal(b, m, deterministic)
}
func (m *IsLockedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsLockedResponse.Merge(m, src)
}
func (m *IsLockedResponse) XXX_Size() int {
	return xxx_messageInfo_IsLockedResponse.Size(m)
}
func (m *IsLockedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IsLockedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IsLockedResponse proto.InternalMessageInfo

func (m *IsLockedResponse) GetHeaders() *headers.SessionResponseHeaders {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *IsLockedResponse) GetIsLocked() bool {
	if m != nil {
		return m.IsLocked
	}
	return false
}

func init() {
	proto.RegisterType((*LockId)(nil), "atomix.lock.LockId")
	proto.RegisterType((*CreateRequest)(nil), "atomix.lock.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "atomix.lock.CreateResponse")
	proto.RegisterType((*KeepAliveRequest)(nil), "atomix.lock.KeepAliveRequest")
	proto.RegisterType((*KeepAliveResponse)(nil), "atomix.lock.KeepAliveResponse")
	proto.RegisterType((*CloseRequest)(nil), "atomix.lock.CloseRequest")
	proto.RegisterType((*CloseResponse)(nil), "atomix.lock.CloseResponse")
	proto.RegisterType((*LockRequest)(nil), "atomix.lock.LockRequest")
	proto.RegisterType((*LockResponse)(nil), "atomix.lock.LockResponse")
	proto.RegisterType((*UnlockRequest)(nil), "atomix.lock.UnlockRequest")
	proto.RegisterType((*UnlockResponse)(nil), "atomix.lock.UnlockResponse")
	proto.RegisterType((*IsLockedRequest)(nil), "atomix.lock.IsLockedRequest")
	proto.RegisterType((*IsLockedResponse)(nil), "atomix.lock.IsLockedResponse")
}

func init() { proto.RegisterFile("lock/lock.proto", fileDescriptor_ebe517841b49c3eb) }

var fileDescriptor_ebe517841b49c3eb = []byte{
	// 634 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0xd1, 0x6e, 0xda, 0x30,
	0x14, 0x6d, 0x80, 0x02, 0xbd, 0x40, 0xe9, 0x5c, 0x4d, 0x0d, 0xd9, 0x8a, 0xaa, 0x54, 0xdd, 0xfa,
	0x14, 0x24, 0xfa, 0x32, 0x69, 0xaa, 0xd6, 0x95, 0x3e, 0x94, 0x8d, 0x4a, 0x2c, 0xd5, 0x9e, 0xa7,
	0x40, 0x0c, 0xf3, 0x9a, 0xc4, 0xa9, 0x93, 0xa0, 0xf5, 0x2b, 0xf6, 0x1b, 0x7b, 0xdd, 0x6f, 0xed,
	0x2b, 0xa6, 0xd8, 0x71, 0x96, 0x04, 0x90, 0x86, 0x56, 0xf5, 0x05, 0x62, 0xdf, 0xeb, 0x73, 0xce,
	0x3d, 0xd7, 0xbe, 0xd0, 0x76, 0xe8, 0xf4, 0xae, 0x17, 0xff, 0x18, 0x3e, 0xa3, 0x21, 0x45, 0x0d,
	0x2b, 0xa4, 0x2e, 0xf9, 0x6e, 0xc4, 0x5b, 0x5a, 0x77, 0x4e, 0xe9, 0xdc, 0xc1, 0x3d, 0x1e, 0x9a,
	0x44, 0xb3, 0x9e, 0x1d, 0x31, 0x2b, 0x24, 0xd4, 0x13, 0xc9, 0xda, 0x01, 0xff, 0x9b, 0x52, 0xa7,
	0x27, 0x3f, 0x92, 0xc0, 0xf3, 0xaf, 0xd8, 0xb2, 0x31, 0x0b, 0x7a, 0xc9, 0xbf, 0xd8, 0xd6, 0x7f,
	0x2b, 0x50, 0x1d, 0xd1, 0xe9, 0xdd, 0xd0, 0x46, 0x08, 0x2a, 0x9e, 0xe5, 0x62, 0x55, 0x39, 0x52,
	0x4e, 0x77, 0x4c, 0xfe, 0x8d, 0xde, 0x40, 0x85, 0x59, 0xb3, 0x50, 0x2d, 0x1d, 0x29, 0xa7, 0x8d,
	0xbe, 0x6e, 0x24, 0x52, 0x52, 0xec, 0x9b, 0xc8, 0x09, 0x89, 0x69, 0xcd, 0xc2, 0x71, 0xb2, 0x73,
	0xbd, 0x65, 0xf2, 0x13, 0x68, 0x04, 0x2d, 0x37, 0x0e, 0x7e, 0xf1, 0x19, 0x71, 0x2d, 0xf6, 0xa0,
	0x96, 0x39, 0xc4, 0xc9, 0x6a, 0x88, 0xb1, 0x48, 0xca, 0xa0, 0x34, 0xdd, 0xcc, 0x3e, 0x7a, 0x0b,
	0x65, 0x87, 0xce, 0xd5, 0x0a, 0xc7, 0x78, 0xbd, 0x84, 0x71, 0x45, 0x82, 0x90, 0x91, 0x49, 0x14,
	0x62, 0x7b, 0x44, 0xe7, 0x19, 0x94, 0xf8, 0xd4, 0x65, 0x0d, 0xb6, 0x45, 0xb1, 0x04, 0x5a, 0x03,
	0x86, 0xad, 0x10, 0x9b, 0xf8, 0x3e, 0xc2, 0x41, 0x88, 0x8e, 0xa1, 0x44, 0x6c, 0x5e, 0x70, 0xa3,
	0xbf, 0x6f, 0x64, 0x7c, 0x36, 0x84, 0x27, 0x66, 0x89, 0xd8, 0xe8, 0x0c, 0x6a, 0x21, 0x71, 0x31,
	0x8d, 0xa4, 0x0d, 0x1d, 0x43, 0x34, 0xc1, 0x90, 0x4d, 0x30, 0xae, 0x92, 0x26, 0x98, 0x32, 0x53,
	0xff, 0x00, 0xbb, 0x92, 0x2a, 0xf0, 0xa9, 0x17, 0xc4, 0x56, 0xd6, 0x12, 0xeb, 0x13, 0xc2, 0xae,
	0x24, 0x94, 0x1d, 0xb9, 0xc5, 0x41, 0x40, 0xa8, 0x77, 0x2d, 0x96, 0xa6, 0x4c, 0xd7, 0xef, 0x61,
	0xef, 0x23, 0xc6, 0xfe, 0x7b, 0x87, 0x2c, 0x36, 0x53, 0x9e, 0xa1, 0x2c, 0x6d, 0x46, 0x79, 0x03,
	0xcf, 0x32, 0x94, 0xff, 0x5d, 0x81, 0x0b, 0xcd, 0x81, 0x43, 0x83, 0xa7, 0x52, 0xdf, 0x86, 0x56,
	0x42, 0x27, 0x94, 0xeb, 0x3f, 0x15, 0x68, 0xc4, 0xc8, 0x1b, 0xf1, 0xbf, 0x2b, 0xf2, 0x9f, 0xac,
	0xe1, 0x1f, 0x50, 0xd7, 0xb5, 0x3c, 0xbb, 0x28, 0x23, 0x7b, 0x71, 0xca, 0xff, 0x7c, 0x71, 0xbe,
	0x41, 0x53, 0x28, 0x4d, 0x4c, 0xbf, 0x28, 0x9a, 0xfe, 0x6a, 0x8d, 0x0a, 0x79, 0x62, 0x49, 0x86,
	0x0a, 0xb5, 0x05, 0x66, 0x71, 0x0a, 0xaf, 0xa3, 0x62, 0xca, 0xa5, 0xfe, 0x43, 0x81, 0xd6, 0x67,
	0xcf, 0x79, 0x72, 0x63, 0x32, 0x8a, 0xca, 0x79, 0x45, 0x1e, 0xec, 0x4a, 0x41, 0x8f, 0x56, 0xbf,
	0x06, 0xf5, 0x88, 0x63, 0x62, 0x9b, 0xeb, 0xad, 0x9b, 0xe9, 0x3a, 0x76, 0xa0, 0x3d, 0x0c, 0x46,
	0x7c, 0xb1, 0x91, 0x07, 0xe7, 0x45, 0x0f, 0x8e, 0xd7, 0xc8, 0xfa, 0x14, 0x61, 0xf6, 0xb0, 0x81,
	0x03, 0x3e, 0xec, 0xfd, 0x15, 0xf4, 0x98, 0x1e, 0x90, 0x04, 0x55, 0x7a, 0x20, 0xd7, 0xfd, 0x5f,
	0x65, 0xf1, 0x38, 0x6e, 0x31, 0x5b, 0x90, 0x29, 0x46, 0x03, 0xa8, 0x8a, 0xd1, 0x85, 0xb4, 0x5c,
	0xf5, 0xb9, 0xd1, 0xa9, 0xbd, 0x58, 0x19, 0x4b, 0xde, 0xdb, 0x16, 0x1a, 0xc1, 0x4e, 0x3a, 0x40,
	0xd0, 0x61, 0x2e, 0xb7, 0x38, 0xcb, 0xb4, 0xee, 0xba, 0x70, 0x8a, 0x76, 0x01, 0xdb, 0xfc, 0x41,
	0xa3, 0x4e, 0x9e, 0x35, 0x33, 0x53, 0x34, 0x6d, 0x55, 0x28, 0x45, 0x38, 0x87, 0x4a, 0x5c, 0x23,
	0x52, 0x97, 0x1a, 0x2a, 0xcf, 0x77, 0x56, 0x44, 0xd2, 0xe3, 0x03, 0xa8, 0x8a, 0x7b, 0x59, 0xf0,
	0x24, 0xf7, 0x7a, 0x0a, 0x9e, 0xe4, 0x2f, 0xb2, 0xbe, 0x85, 0x86, 0x50, 0x97, 0xad, 0x45, 0x2f,
	0x73, 0xa9, 0x85, 0x2b, 0xa8, 0x1d, 0xae, 0x89, 0x4a, 0xa8, 0xcb, 0x03, 0xd8, 0x27, 0x54, 0x26,
	0xcd, 0x99, 0x3f, 0xe5, 0x99, 0x63, 0x65, 0x52, 0xe5, 0xa3, 0xe5, 0xec, 0x4f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x32, 0xd9, 0x2c, 0x83, 0x46, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LockServiceClient is the client API for LockService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LockServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	KeepAlive(ctx context.Context, in *KeepAliveRequest, opts ...grpc.CallOption) (*KeepAliveResponse, error)
	Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error)
	Lock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*LockResponse, error)
	Unlock(ctx context.Context, in *UnlockRequest, opts ...grpc.CallOption) (*UnlockResponse, error)
	IsLocked(ctx context.Context, in *IsLockedRequest, opts ...grpc.CallOption) (*IsLockedResponse, error)
}

type lockServiceClient struct {
	cc *grpc.ClientConn
}

func NewLockServiceClient(cc *grpc.ClientConn) LockServiceClient {
	return &lockServiceClient{cc}
}

func (c *lockServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/atomix.lock.LockService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lockServiceClient) KeepAlive(ctx context.Context, in *KeepAliveRequest, opts ...grpc.CallOption) (*KeepAliveResponse, error) {
	out := new(KeepAliveResponse)
	err := c.cc.Invoke(ctx, "/atomix.lock.LockService/KeepAlive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lockServiceClient) Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error) {
	out := new(CloseResponse)
	err := c.cc.Invoke(ctx, "/atomix.lock.LockService/Close", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lockServiceClient) Lock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*LockResponse, error) {
	out := new(LockResponse)
	err := c.cc.Invoke(ctx, "/atomix.lock.LockService/Lock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lockServiceClient) Unlock(ctx context.Context, in *UnlockRequest, opts ...grpc.CallOption) (*UnlockResponse, error) {
	out := new(UnlockResponse)
	err := c.cc.Invoke(ctx, "/atomix.lock.LockService/Unlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lockServiceClient) IsLocked(ctx context.Context, in *IsLockedRequest, opts ...grpc.CallOption) (*IsLockedResponse, error) {
	out := new(IsLockedResponse)
	err := c.cc.Invoke(ctx, "/atomix.lock.LockService/IsLocked", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LockServiceServer is the server API for LockService service.
type LockServiceServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	KeepAlive(context.Context, *KeepAliveRequest) (*KeepAliveResponse, error)
	Close(context.Context, *CloseRequest) (*CloseResponse, error)
	Lock(context.Context, *LockRequest) (*LockResponse, error)
	Unlock(context.Context, *UnlockRequest) (*UnlockResponse, error)
	IsLocked(context.Context, *IsLockedRequest) (*IsLockedResponse, error)
}

// UnimplementedLockServiceServer can be embedded to have forward compatible implementations.
type UnimplementedLockServiceServer struct {
}

func (*UnimplementedLockServiceServer) Create(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedLockServiceServer) KeepAlive(ctx context.Context, req *KeepAliveRequest) (*KeepAliveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeepAlive not implemented")
}
func (*UnimplementedLockServiceServer) Close(ctx context.Context, req *CloseRequest) (*CloseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Close not implemented")
}
func (*UnimplementedLockServiceServer) Lock(ctx context.Context, req *LockRequest) (*LockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lock not implemented")
}
func (*UnimplementedLockServiceServer) Unlock(ctx context.Context, req *UnlockRequest) (*UnlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unlock not implemented")
}
func (*UnimplementedLockServiceServer) IsLocked(ctx context.Context, req *IsLockedRequest) (*IsLockedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsLocked not implemented")
}

func RegisterLockServiceServer(s *grpc.Server, srv LockServiceServer) {
	s.RegisterService(&_LockService_serviceDesc, srv)
}

func _LockService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/atomix.lock.LockService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LockService_KeepAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeepAliveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockServiceServer).KeepAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/atomix.lock.LockService/KeepAlive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockServiceServer).KeepAlive(ctx, req.(*KeepAliveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LockService_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockServiceServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/atomix.lock.LockService/Close",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockServiceServer).Close(ctx, req.(*CloseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LockService_Lock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockServiceServer).Lock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/atomix.lock.LockService/Lock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockServiceServer).Lock(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LockService_Unlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockServiceServer).Unlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/atomix.lock.LockService/Unlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockServiceServer).Unlock(ctx, req.(*UnlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LockService_IsLocked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsLockedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockServiceServer).IsLocked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/atomix.lock.LockService/IsLocked",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockServiceServer).IsLocked(ctx, req.(*IsLockedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LockService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "atomix.lock.LockService",
	HandlerType: (*LockServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _LockService_Create_Handler,
		},
		{
			MethodName: "KeepAlive",
			Handler:    _LockService_KeepAlive_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _LockService_Close_Handler,
		},
		{
			MethodName: "Lock",
			Handler:    _LockService_Lock_Handler,
		},
		{
			MethodName: "Unlock",
			Handler:    _LockService_Unlock_Handler,
		},
		{
			MethodName: "IsLocked",
			Handler:    _LockService_IsLocked_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lock/lock.proto",
}
