// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol/protocol.proto

package atomix_protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Multi-Raft protocol
type MultiRaftProtocol struct {
	Group                string   `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiRaftProtocol) Reset()         { *m = MultiRaftProtocol{} }
func (m *MultiRaftProtocol) String() string { return proto.CompactTextString(m) }
func (*MultiRaftProtocol) ProtoMessage()    {}
func (*MultiRaftProtocol) Descriptor() ([]byte, []int) {
	return fileDescriptor_87968d26f3046c60, []int{0}
}

func (m *MultiRaftProtocol) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiRaftProtocol.Unmarshal(m, b)
}
func (m *MultiRaftProtocol) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiRaftProtocol.Marshal(b, m, deterministic)
}
func (m *MultiRaftProtocol) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiRaftProtocol.Merge(m, src)
}
func (m *MultiRaftProtocol) XXX_Size() int {
	return xxx_messageInfo_MultiRaftProtocol.Size(m)
}
func (m *MultiRaftProtocol) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiRaftProtocol.DiscardUnknown(m)
}

var xxx_messageInfo_MultiRaftProtocol proto.InternalMessageInfo

func (m *MultiRaftProtocol) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

// Multi-primary protocol
type MultiPrimaryProtocol struct {
	Group                string   `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiPrimaryProtocol) Reset()         { *m = MultiPrimaryProtocol{} }
func (m *MultiPrimaryProtocol) String() string { return proto.CompactTextString(m) }
func (*MultiPrimaryProtocol) ProtoMessage()    {}
func (*MultiPrimaryProtocol) Descriptor() ([]byte, []int) {
	return fileDescriptor_87968d26f3046c60, []int{1}
}

func (m *MultiPrimaryProtocol) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiPrimaryProtocol.Unmarshal(m, b)
}
func (m *MultiPrimaryProtocol) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiPrimaryProtocol.Marshal(b, m, deterministic)
}
func (m *MultiPrimaryProtocol) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiPrimaryProtocol.Merge(m, src)
}
func (m *MultiPrimaryProtocol) XXX_Size() int {
	return xxx_messageInfo_MultiPrimaryProtocol.Size(m)
}
func (m *MultiPrimaryProtocol) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiPrimaryProtocol.DiscardUnknown(m)
}

var xxx_messageInfo_MultiPrimaryProtocol proto.InternalMessageInfo

func (m *MultiPrimaryProtocol) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

// Distributed log protocol
type DistributedLogProtocol struct {
	Group                string   `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Partitions           int32    `protobuf:"varint,2,opt,name=partitions,proto3" json:"partitions,omitempty"`
	ReplicationFactor    int32    `protobuf:"varint,3,opt,name=replication_factor,json=replicationFactor,proto3" json:"replication_factor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DistributedLogProtocol) Reset()         { *m = DistributedLogProtocol{} }
func (m *DistributedLogProtocol) String() string { return proto.CompactTextString(m) }
func (*DistributedLogProtocol) ProtoMessage()    {}
func (*DistributedLogProtocol) Descriptor() ([]byte, []int) {
	return fileDescriptor_87968d26f3046c60, []int{2}
}

func (m *DistributedLogProtocol) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistributedLogProtocol.Unmarshal(m, b)
}
func (m *DistributedLogProtocol) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistributedLogProtocol.Marshal(b, m, deterministic)
}
func (m *DistributedLogProtocol) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistributedLogProtocol.Merge(m, src)
}
func (m *DistributedLogProtocol) XXX_Size() int {
	return xxx_messageInfo_DistributedLogProtocol.Size(m)
}
func (m *DistributedLogProtocol) XXX_DiscardUnknown() {
	xxx_messageInfo_DistributedLogProtocol.DiscardUnknown(m)
}

var xxx_messageInfo_DistributedLogProtocol proto.InternalMessageInfo

func (m *DistributedLogProtocol) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *DistributedLogProtocol) GetPartitions() int32 {
	if m != nil {
		return m.Partitions
	}
	return 0
}

func (m *DistributedLogProtocol) GetReplicationFactor() int32 {
	if m != nil {
		return m.ReplicationFactor
	}
	return 0
}

// Gossip protocol
type GossipProtocol struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GossipProtocol) Reset()         { *m = GossipProtocol{} }
func (m *GossipProtocol) String() string { return proto.CompactTextString(m) }
func (*GossipProtocol) ProtoMessage()    {}
func (*GossipProtocol) Descriptor() ([]byte, []int) {
	return fileDescriptor_87968d26f3046c60, []int{3}
}

func (m *GossipProtocol) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GossipProtocol.Unmarshal(m, b)
}
func (m *GossipProtocol) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GossipProtocol.Marshal(b, m, deterministic)
}
func (m *GossipProtocol) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GossipProtocol.Merge(m, src)
}
func (m *GossipProtocol) XXX_Size() int {
	return xxx_messageInfo_GossipProtocol.Size(m)
}
func (m *GossipProtocol) XXX_DiscardUnknown() {
	xxx_messageInfo_GossipProtocol.DiscardUnknown(m)
}

var xxx_messageInfo_GossipProtocol proto.InternalMessageInfo

// CRDT protocol
type CrdtProtocol struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrdtProtocol) Reset()         { *m = CrdtProtocol{} }
func (m *CrdtProtocol) String() string { return proto.CompactTextString(m) }
func (*CrdtProtocol) ProtoMessage()    {}
func (*CrdtProtocol) Descriptor() ([]byte, []int) {
	return fileDescriptor_87968d26f3046c60, []int{4}
}

func (m *CrdtProtocol) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrdtProtocol.Unmarshal(m, b)
}
func (m *CrdtProtocol) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrdtProtocol.Marshal(b, m, deterministic)
}
func (m *CrdtProtocol) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrdtProtocol.Merge(m, src)
}
func (m *CrdtProtocol) XXX_Size() int {
	return xxx_messageInfo_CrdtProtocol.Size(m)
}
func (m *CrdtProtocol) XXX_DiscardUnknown() {
	xxx_messageInfo_CrdtProtocol.DiscardUnknown(m)
}

var xxx_messageInfo_CrdtProtocol proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MultiRaftProtocol)(nil), "atomix.protocol.MultiRaftProtocol")
	proto.RegisterType((*MultiPrimaryProtocol)(nil), "atomix.protocol.MultiPrimaryProtocol")
	proto.RegisterType((*DistributedLogProtocol)(nil), "atomix.protocol.DistributedLogProtocol")
	proto.RegisterType((*GossipProtocol)(nil), "atomix.protocol.GossipProtocol")
	proto.RegisterType((*CrdtProtocol)(nil), "atomix.protocol.CrdtProtocol")
}

func init() { proto.RegisterFile("protocol/protocol.proto", fileDescriptor_87968d26f3046c60) }

var fileDescriptor_87968d26f3046c60 = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xcd, 0x4a, 0xc4, 0x30,
	0x10, 0xc7, 0x89, 0xb2, 0x82, 0x83, 0xac, 0x6e, 0x58, 0xdc, 0x82, 0x20, 0x4b, 0x4e, 0x15, 0xb4,
	0x1e, 0x7c, 0x03, 0x15, 0xbd, 0x28, 0x94, 0xbe, 0x80, 0xa4, 0xe9, 0x07, 0x03, 0xad, 0x13, 0x26,
	0x53, 0xd0, 0x83, 0xef, 0x2e, 0xc6, 0xb6, 0xf4, 0xa4, 0xb7, 0xff, 0xc7, 0x0f, 0x86, 0xf9, 0xc3,
	0xce, 0x33, 0x09, 0x39, 0xea, 0x6e, 0x27, 0x91, 0x45, 0xa1, 0x4f, 0xad, 0x50, 0x8f, 0x1f, 0xd9,
	0x14, 0x9b, 0x2b, 0xd8, 0xbc, 0x0e, 0x9d, 0x60, 0x61, 0x1b, 0xc9, 0xc7, 0x50, 0x6f, 0x61, 0xd5,
	0x32, 0x0d, 0x3e, 0x51, 0x7b, 0x95, 0x1e, 0x17, 0xbf, 0xc6, 0x5c, 0xc3, 0x36, 0xa2, 0x39, 0x63,
	0x6f, 0xf9, 0xf3, 0x1f, 0xfa, 0x0b, 0xce, 0x1f, 0x31, 0x08, 0x63, 0x39, 0x48, 0x5d, 0xbd, 0x50,
	0xfb, 0x37, 0xaf, 0x2f, 0x01, 0xbc, 0x65, 0x41, 0x41, 0x7a, 0x0f, 0xc9, 0xc1, 0x5e, 0xa5, 0xab,
	0x62, 0x91, 0xe8, 0x1b, 0xd0, 0x5c, 0xfb, 0x0e, 0x9d, 0xfd, 0xf1, 0x6f, 0x8d, 0x75, 0x42, 0x9c,
	0x1c, 0x46, 0x6e, 0xb3, 0x68, 0x9e, 0x62, 0x61, 0xce, 0x60, 0xfd, 0x4c, 0x21, 0xa0, 0x9f, 0xce,
	0x9a, 0x35, 0x9c, 0x3c, 0x70, 0x35, 0x3f, 0x79, 0x7f, 0x01, 0x3b, 0xa4, 0x6c, 0xdc, 0xa3, 0x65,
	0xef, 0xe6, 0x51, 0x72, 0x55, 0x1e, 0x45, 0x7d, 0xf7, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x3c, 0xf0,
	0xf1, 0xcd, 0x49, 0x01, 0x00, 0x00,
}
