// Code generated by protoc-gen-go. DO NOT EDIT.
// source: log.proto

package atomix_log

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Distributed log ID
type LogId struct {
	// Types that are valid to be assigned to Proto:
	//	*LogId_Log
	Proto                isLogId_Proto `protobuf_oneof:"proto"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *LogId) Reset()         { *m = LogId{} }
func (m *LogId) String() string { return proto.CompactTextString(m) }
func (*LogId) ProtoMessage()    {}
func (*LogId) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{0}
}

func (m *LogId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogId.Unmarshal(m, b)
}
func (m *LogId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogId.Marshal(b, m, deterministic)
}
func (m *LogId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogId.Merge(m, src)
}
func (m *LogId) XXX_Size() int {
	return xxx_messageInfo_LogId.Size(m)
}
func (m *LogId) XXX_DiscardUnknown() {
	xxx_messageInfo_LogId.DiscardUnknown(m)
}

var xxx_messageInfo_LogId proto.InternalMessageInfo

type isLogId_Proto interface {
	isLogId_Proto()
}

type LogId_Log struct {
	Log *DistributedLogProtocol `protobuf:"bytes,1,opt,name=log,proto3,oneof"`
}

func (*LogId_Log) isLogId_Proto() {}

func (m *LogId) GetProto() isLogId_Proto {
	if m != nil {
		return m.Proto
	}
	return nil
}

func (m *LogId) GetLog() *DistributedLogProtocol {
	if x, ok := m.GetProto().(*LogId_Log); ok {
		return x.Log
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*LogId) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*LogId_Log)(nil),
	}
}

type ProduceRequest struct {
	Id                   *LogId   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Partition            int32    `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProduceRequest) Reset()         { *m = ProduceRequest{} }
func (m *ProduceRequest) String() string { return proto.CompactTextString(m) }
func (*ProduceRequest) ProtoMessage()    {}
func (*ProduceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{1}
}

func (m *ProduceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProduceRequest.Unmarshal(m, b)
}
func (m *ProduceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProduceRequest.Marshal(b, m, deterministic)
}
func (m *ProduceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProduceRequest.Merge(m, src)
}
func (m *ProduceRequest) XXX_Size() int {
	return xxx_messageInfo_ProduceRequest.Size(m)
}
func (m *ProduceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProduceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProduceRequest proto.InternalMessageInfo

func (m *ProduceRequest) GetId() *LogId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ProduceRequest) GetPartition() int32 {
	if m != nil {
		return m.Partition
	}
	return 0
}

func (m *ProduceRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type ProduceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProduceResponse) Reset()         { *m = ProduceResponse{} }
func (m *ProduceResponse) String() string { return proto.CompactTextString(m) }
func (*ProduceResponse) ProtoMessage()    {}
func (*ProduceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{2}
}

func (m *ProduceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProduceResponse.Unmarshal(m, b)
}
func (m *ProduceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProduceResponse.Marshal(b, m, deterministic)
}
func (m *ProduceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProduceResponse.Merge(m, src)
}
func (m *ProduceResponse) XXX_Size() int {
	return xxx_messageInfo_ProduceResponse.Size(m)
}
func (m *ProduceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProduceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProduceResponse proto.InternalMessageInfo

type ConsumeRequest struct {
	Id                   *LogId   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Partition            int32    `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsumeRequest) Reset()         { *m = ConsumeRequest{} }
func (m *ConsumeRequest) String() string { return proto.CompactTextString(m) }
func (*ConsumeRequest) ProtoMessage()    {}
func (*ConsumeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{3}
}

func (m *ConsumeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsumeRequest.Unmarshal(m, b)
}
func (m *ConsumeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsumeRequest.Marshal(b, m, deterministic)
}
func (m *ConsumeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumeRequest.Merge(m, src)
}
func (m *ConsumeRequest) XXX_Size() int {
	return xxx_messageInfo_ConsumeRequest.Size(m)
}
func (m *ConsumeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumeRequest proto.InternalMessageInfo

func (m *ConsumeRequest) GetId() *LogId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ConsumeRequest) GetPartition() int32 {
	if m != nil {
		return m.Partition
	}
	return 0
}

type LogRecord struct {
	Offset               uint64   `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Timestamp            uint64   `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogRecord) Reset()         { *m = LogRecord{} }
func (m *LogRecord) String() string { return proto.CompactTextString(m) }
func (*LogRecord) ProtoMessage()    {}
func (*LogRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{4}
}

func (m *LogRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogRecord.Unmarshal(m, b)
}
func (m *LogRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogRecord.Marshal(b, m, deterministic)
}
func (m *LogRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogRecord.Merge(m, src)
}
func (m *LogRecord) XXX_Size() int {
	return xxx_messageInfo_LogRecord.Size(m)
}
func (m *LogRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_LogRecord.DiscardUnknown(m)
}

var xxx_messageInfo_LogRecord proto.InternalMessageInfo

func (m *LogRecord) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *LogRecord) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *LogRecord) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*LogId)(nil), "atomix.log.LogId")
	proto.RegisterType((*ProduceRequest)(nil), "atomix.log.ProduceRequest")
	proto.RegisterType((*ProduceResponse)(nil), "atomix.log.ProduceResponse")
	proto.RegisterType((*ConsumeRequest)(nil), "atomix.log.ConsumeRequest")
	proto.RegisterType((*LogRecord)(nil), "atomix.log.LogRecord")
}

func init() { proto.RegisterFile("log.proto", fileDescriptor_a153da538f858886) }

var fileDescriptor_a153da538f858886 = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0xc1, 0x4f, 0xc2, 0x30,
	0x14, 0xc6, 0x29, 0x30, 0x08, 0x4f, 0x83, 0xa1, 0x51, 0x42, 0xa6, 0x07, 0xdc, 0xc5, 0x9d, 0x16,
	0x83, 0x47, 0x2f, 0x06, 0x8d, 0xd1, 0x64, 0x26, 0x58, 0x0f, 0x9e, 0xc7, 0x5a, 0x9a, 0x26, 0x1b,
	0x6f, 0xb6, 0x1d, 0xf1, 0x2f, 0xf1, 0xef, 0x35, 0x6c, 0x15, 0x9c, 0xe1, 0xe8, 0xb1, 0xdf, 0x7b,
	0xef, 0xf7, 0xde, 0xf7, 0x15, 0x06, 0x19, 0xca, 0xa8, 0xd0, 0x68, 0x91, 0x42, 0x62, 0x31, 0x57,
	0x9f, 0x51, 0x86, 0xd2, 0x1f, 0x56, 0x52, 0x8a, 0x59, 0x5d, 0x0b, 0x5e, 0xc0, 0x8b, 0x51, 0x3e,
	0x73, 0x7a, 0x0b, 0x9d, 0x0c, 0xe5, 0x84, 0x4c, 0x49, 0x78, 0x34, 0xbb, 0x8a, 0xdc, 0xc8, 0xae,
	0xfb, 0x41, 0x19, 0xab, 0xd5, 0xb2, 0xb4, 0x82, 0xc7, 0x28, 0x17, 0x4e, 0x7e, 0x6a, 0xb1, 0xed,
	0xd4, 0xbc, 0x0f, 0x5e, 0x8d, 0x93, 0x30, 0x5c, 0x68, 0xe4, 0x65, 0x2a, 0x98, 0xf8, 0x28, 0x85,
	0xb1, 0xf4, 0x12, 0xda, 0x8a, 0x3b, 0xec, 0x28, 0xda, 0x5f, 0x12, 0x55, 0x6b, 0x59, 0x5b, 0x71,
	0x7a, 0x01, 0x83, 0x22, 0xd1, 0x56, 0x59, 0x85, 0xeb, 0x49, 0x7b, 0x4a, 0x42, 0x8f, 0xed, 0x05,
	0x7a, 0x0a, 0xde, 0x26, 0xc9, 0x4a, 0x31, 0xe9, 0x4c, 0x49, 0x78, 0xcc, 0xea, 0x47, 0x30, 0x82,
	0x93, 0xdd, 0x22, 0x53, 0xe0, 0xda, 0x88, 0xe0, 0x15, 0x86, 0xf7, 0xb8, 0x36, 0x65, 0xfe, 0x6f,
	0xbb, 0x83, 0x77, 0x18, 0xc4, 0x28, 0x99, 0x48, 0x51, 0x73, 0x3a, 0x86, 0x1e, 0xae, 0x56, 0x46,
	0xd8, 0x8a, 0xd8, 0x65, 0xee, 0xb5, 0x45, 0x58, 0x95, 0x0b, 0x63, 0x93, 0xbc, 0xa8, 0x10, 0x5d,
	0xb6, 0x17, 0x0e, 0x9f, 0x3f, 0xfb, 0x22, 0x00, 0x31, 0xca, 0x37, 0xa1, 0x37, 0x2a, 0x15, 0xf4,
	0x11, 0xfa, 0xce, 0x0d, 0xf5, 0x7f, 0xdf, 0xd9, 0xcc, 0xd2, 0x3f, 0x3f, 0x58, 0x73, 0xf6, 0x5b,
	0x21, 0xa1, 0x77, 0xd0, 0x77, 0x11, 0x34, 0x39, 0xcd, 0x5c, 0xfc, 0xb3, 0x3f, 0x59, 0xd4, 0x06,
	0x83, 0xd6, 0x35, 0x99, 0x8f, 0x81, 0x2a, 0xfc, 0x29, 0x4b, 0x5d, 0xa4, 0xdb, 0x9e, 0x05, 0x59,
	0xf6, 0xaa, 0xff, 0xbd, 0xf9, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x64, 0xd1, 0xde, 0x39, 0x57, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LogServiceClient is the client API for LogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LogServiceClient interface {
	Produce(ctx context.Context, opts ...grpc.CallOption) (LogService_ProduceClient, error)
	Consume(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (LogService_ConsumeClient, error)
}

type logServiceClient struct {
	cc *grpc.ClientConn
}

func NewLogServiceClient(cc *grpc.ClientConn) LogServiceClient {
	return &logServiceClient{cc}
}

func (c *logServiceClient) Produce(ctx context.Context, opts ...grpc.CallOption) (LogService_ProduceClient, error) {
	stream, err := c.cc.NewStream(ctx, &_LogService_serviceDesc.Streams[0], "/atomix.log.LogService/Produce", opts...)
	if err != nil {
		return nil, err
	}
	x := &logServiceProduceClient{stream}
	return x, nil
}

type LogService_ProduceClient interface {
	Send(*ProduceRequest) error
	CloseAndRecv() (*ProduceResponse, error)
	grpc.ClientStream
}

type logServiceProduceClient struct {
	grpc.ClientStream
}

func (x *logServiceProduceClient) Send(m *ProduceRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *logServiceProduceClient) CloseAndRecv() (*ProduceResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ProduceResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *logServiceClient) Consume(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (LogService_ConsumeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_LogService_serviceDesc.Streams[1], "/atomix.log.LogService/Consume", opts...)
	if err != nil {
		return nil, err
	}
	x := &logServiceConsumeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LogService_ConsumeClient interface {
	Recv() (*LogRecord, error)
	grpc.ClientStream
}

type logServiceConsumeClient struct {
	grpc.ClientStream
}

func (x *logServiceConsumeClient) Recv() (*LogRecord, error) {
	m := new(LogRecord)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LogServiceServer is the server API for LogService service.
type LogServiceServer interface {
	Produce(LogService_ProduceServer) error
	Consume(*ConsumeRequest, LogService_ConsumeServer) error
}

// UnimplementedLogServiceServer can be embedded to have forward compatible implementations.
type UnimplementedLogServiceServer struct {
}

func (*UnimplementedLogServiceServer) Produce(srv LogService_ProduceServer) error {
	return status.Errorf(codes.Unimplemented, "method Produce not implemented")
}
func (*UnimplementedLogServiceServer) Consume(req *ConsumeRequest, srv LogService_ConsumeServer) error {
	return status.Errorf(codes.Unimplemented, "method Consume not implemented")
}

func RegisterLogServiceServer(s *grpc.Server, srv LogServiceServer) {
	s.RegisterService(&_LogService_serviceDesc, srv)
}

func _LogService_Produce_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LogServiceServer).Produce(&logServiceProduceServer{stream})
}

type LogService_ProduceServer interface {
	SendAndClose(*ProduceResponse) error
	Recv() (*ProduceRequest, error)
	grpc.ServerStream
}

type logServiceProduceServer struct {
	grpc.ServerStream
}

func (x *logServiceProduceServer) SendAndClose(m *ProduceResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *logServiceProduceServer) Recv() (*ProduceRequest, error) {
	m := new(ProduceRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _LogService_Consume_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConsumeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LogServiceServer).Consume(m, &logServiceConsumeServer{stream})
}

type LogService_ConsumeServer interface {
	Send(*LogRecord) error
	grpc.ServerStream
}

type logServiceConsumeServer struct {
	grpc.ServerStream
}

func (x *logServiceConsumeServer) Send(m *LogRecord) error {
	return x.ServerStream.SendMsg(m)
}

var _LogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "atomix.log.LogService",
	HandlerType: (*LogServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Produce",
			Handler:       _LogService_Produce_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Consume",
			Handler:       _LogService_Consume_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "log.proto",
}
