// Code generated by protoc-gen-go. DO NOT EDIT.
// source: atomix/headers/headers.proto

package headers

import (
	fmt "fmt"
	primitive "github.com/atomix/atomix-go-client/proto/atomix/primitive"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestHeader struct {
	Name                 *primitive.Name `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SessionId            uint64          `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Index                uint64          `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	SequenceNumber       uint64          `protobuf:"varint,4,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Streams              []*StreamHeader `protobuf:"bytes,5,rep,name=streams,proto3" json:"streams,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RequestHeader) Reset()         { *m = RequestHeader{} }
func (m *RequestHeader) String() string { return proto.CompactTextString(m) }
func (*RequestHeader) ProtoMessage()    {}
func (*RequestHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_95de8fb3e0e30ffd, []int{0}
}

func (m *RequestHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestHeader.Unmarshal(m, b)
}
func (m *RequestHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestHeader.Marshal(b, m, deterministic)
}
func (m *RequestHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestHeader.Merge(m, src)
}
func (m *RequestHeader) XXX_Size() int {
	return xxx_messageInfo_RequestHeader.Size(m)
}
func (m *RequestHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestHeader.DiscardUnknown(m)
}

var xxx_messageInfo_RequestHeader proto.InternalMessageInfo

func (m *RequestHeader) GetName() *primitive.Name {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *RequestHeader) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *RequestHeader) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *RequestHeader) GetSequenceNumber() uint64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *RequestHeader) GetStreams() []*StreamHeader {
	if m != nil {
		return m.Streams
	}
	return nil
}

type ResponseHeader struct {
	SessionId            uint64          `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Index                uint64          `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	SequenceNumber       uint64          `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Streams              []*StreamHeader `protobuf:"bytes,4,rep,name=streams,proto3" json:"streams,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ResponseHeader) Reset()         { *m = ResponseHeader{} }
func (m *ResponseHeader) String() string { return proto.CompactTextString(m) }
func (*ResponseHeader) ProtoMessage()    {}
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_95de8fb3e0e30ffd, []int{1}
}

func (m *ResponseHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseHeader.Unmarshal(m, b)
}
func (m *ResponseHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseHeader.Marshal(b, m, deterministic)
}
func (m *ResponseHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseHeader.Merge(m, src)
}
func (m *ResponseHeader) XXX_Size() int {
	return xxx_messageInfo_ResponseHeader.Size(m)
}
func (m *ResponseHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseHeader proto.InternalMessageInfo

func (m *ResponseHeader) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *ResponseHeader) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ResponseHeader) GetSequenceNumber() uint64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *ResponseHeader) GetStreams() []*StreamHeader {
	if m != nil {
		return m.Streams
	}
	return nil
}

type StreamHeader struct {
	StreamId             uint64   `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Index                uint64   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	LastItemNumber       uint64   `protobuf:"varint,3,opt,name=last_item_number,json=lastItemNumber,proto3" json:"last_item_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamHeader) Reset()         { *m = StreamHeader{} }
func (m *StreamHeader) String() string { return proto.CompactTextString(m) }
func (*StreamHeader) ProtoMessage()    {}
func (*StreamHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_95de8fb3e0e30ffd, []int{2}
}

func (m *StreamHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamHeader.Unmarshal(m, b)
}
func (m *StreamHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamHeader.Marshal(b, m, deterministic)
}
func (m *StreamHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamHeader.Merge(m, src)
}
func (m *StreamHeader) XXX_Size() int {
	return xxx_messageInfo_StreamHeader.Size(m)
}
func (m *StreamHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamHeader.DiscardUnknown(m)
}

var xxx_messageInfo_StreamHeader proto.InternalMessageInfo

func (m *StreamHeader) GetStreamId() uint64 {
	if m != nil {
		return m.StreamId
	}
	return 0
}

func (m *StreamHeader) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *StreamHeader) GetLastItemNumber() uint64 {
	if m != nil {
		return m.LastItemNumber
	}
	return 0
}

func init() {
	proto.RegisterType((*RequestHeader)(nil), "atomix.headers.RequestHeader")
	proto.RegisterType((*ResponseHeader)(nil), "atomix.headers.ResponseHeader")
	proto.RegisterType((*StreamHeader)(nil), "atomix.headers.StreamHeader")
}

func init() { proto.RegisterFile("atomix/headers/headers.proto", fileDescriptor_95de8fb3e0e30ffd) }

var fileDescriptor_95de8fb3e0e30ffd = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x86, 0xc9, 0xda, 0xa9, 0x3b, 0xd3, 0x2a, 0x41, 0xa4, 0xe8, 0x84, 0xb2, 0x1b, 0x8b, 0x17,
	0x15, 0x26, 0xf8, 0x0c, 0xee, 0x66, 0x17, 0xf5, 0x01, 0x4a, 0x66, 0x0f, 0x18, 0x34, 0x69, 0xcd,
	0xc9, 0x64, 0x4f, 0xe4, 0xfb, 0xf8, 0x46, 0xb2, 0x24, 0xa5, 0x4e, 0x18, 0x63, 0x57, 0x49, 0xfe,
	0xef, 0x9c, 0xe4, 0x3b, 0x04, 0x26, 0xc2, 0x36, 0x4a, 0xae, 0x1f, 0xde, 0x50, 0xd4, 0x68, 0xa8,
	0x5b, 0x8b, 0xd6, 0x34, 0xb6, 0xe1, 0x89, 0xa7, 0x45, 0x48, 0xaf, 0xb3, 0x50, 0xdd, 0x1a, 0xa9,
	0xa4, 0x95, 0x5f, 0xd8, 0xef, 0x7c, 0xc7, 0xf4, 0x87, 0xc1, 0x59, 0x89, 0x9f, 0x2b, 0x24, 0xfb,
	0xec, 0x9a, 0xf8, 0x3d, 0xc4, 0x5a, 0x28, 0x4c, 0x59, 0xc6, 0xf2, 0xf1, 0xec, 0xaa, 0x08, 0x57,
	0xf6, 0x8d, 0x0b, 0xa1, 0xb0, 0x74, 0x35, 0xfc, 0x16, 0x80, 0x90, 0x48, 0x36, 0xba, 0x92, 0x75,
	0x3a, 0xc8, 0x58, 0x1e, 0x97, 0xa3, 0x90, 0xcc, 0x6b, 0x7e, 0x09, 0x43, 0xa9, 0x6b, 0x5c, 0xa7,
	0x91, 0x23, 0xfe, 0xc0, 0xef, 0xe0, 0x9c, 0x36, 0x2f, 0xea, 0x57, 0xac, 0xf4, 0x4a, 0x2d, 0xd1,
	0xa4, 0xb1, 0xe3, 0x49, 0x17, 0x2f, 0x5c, 0xca, 0x9f, 0xe0, 0x98, 0xac, 0x41, 0xa1, 0x28, 0x1d,
	0x66, 0x51, 0x3e, 0x9e, 0x4d, 0x8a, 0xed, 0xf9, 0x8a, 0x17, 0x87, 0xbd, 0x78, 0xd9, 0x15, 0x4f,
	0xbf, 0x19, 0x24, 0x25, 0x52, 0xdb, 0x68, 0xc2, 0x30, 0xd4, 0xb6, 0x28, 0xdb, 0x29, 0x3a, 0xd8,
	0x23, 0x1a, 0xed, 0x13, 0x8d, 0x0f, 0x11, 0x7d, 0x87, 0xd3, 0xbf, 0x80, 0xdf, 0xc0, 0xc8, 0xa3,
	0x5e, 0xf2, 0xc4, 0x07, 0x3b, 0x1d, 0x73, 0xb8, 0xf8, 0x10, 0x64, 0x2b, 0x69, 0x51, 0xfd, 0x93,
	0xdc, 0xe4, 0x73, 0x8b, 0xca, 0x4b, 0x2e, 0x8f, 0xdc, 0x87, 0x3f, 0xfe, 0x06, 0x00, 0x00, 0xff,
	0xff, 0x19, 0x5b, 0xda, 0xc9, 0x42, 0x02, 0x00, 0x00,
}
