// Code generated by protoc-gen-go. DO NOT EDIT.
// source: primitives/primitives.proto

package primitives

import (
	context "context"
	fmt "fmt"
	_ "github.com/atomix/atomix-go/proto/protocol"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PrimitiveInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimitiveInfo) Reset()         { *m = PrimitiveInfo{} }
func (m *PrimitiveInfo) String() string { return proto.CompactTextString(m) }
func (*PrimitiveInfo) ProtoMessage()    {}
func (*PrimitiveInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_18b8a7b9552a23a1, []int{0}
}

func (m *PrimitiveInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimitiveInfo.Unmarshal(m, b)
}
func (m *PrimitiveInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimitiveInfo.Marshal(b, m, deterministic)
}
func (m *PrimitiveInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimitiveInfo.Merge(m, src)
}
func (m *PrimitiveInfo) XXX_Size() int {
	return xxx_messageInfo_PrimitiveInfo.Size(m)
}
func (m *PrimitiveInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimitiveInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PrimitiveInfo proto.InternalMessageInfo

func (m *PrimitiveInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PrimitiveInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type GetPrimitivesRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPrimitivesRequest) Reset()         { *m = GetPrimitivesRequest{} }
func (m *GetPrimitivesRequest) String() string { return proto.CompactTextString(m) }
func (*GetPrimitivesRequest) ProtoMessage()    {}
func (*GetPrimitivesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_18b8a7b9552a23a1, []int{1}
}

func (m *GetPrimitivesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPrimitivesRequest.Unmarshal(m, b)
}
func (m *GetPrimitivesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPrimitivesRequest.Marshal(b, m, deterministic)
}
func (m *GetPrimitivesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPrimitivesRequest.Merge(m, src)
}
func (m *GetPrimitivesRequest) XXX_Size() int {
	return xxx_messageInfo_GetPrimitivesRequest.Size(m)
}
func (m *GetPrimitivesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPrimitivesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPrimitivesRequest proto.InternalMessageInfo

func (m *GetPrimitivesRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type GetPrimitivesResponse struct {
	Info                 []*PrimitiveInfo `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetPrimitivesResponse) Reset()         { *m = GetPrimitivesResponse{} }
func (m *GetPrimitivesResponse) String() string { return proto.CompactTextString(m) }
func (*GetPrimitivesResponse) ProtoMessage()    {}
func (*GetPrimitivesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_18b8a7b9552a23a1, []int{2}
}

func (m *GetPrimitivesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPrimitivesResponse.Unmarshal(m, b)
}
func (m *GetPrimitivesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPrimitivesResponse.Marshal(b, m, deterministic)
}
func (m *GetPrimitivesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPrimitivesResponse.Merge(m, src)
}
func (m *GetPrimitivesResponse) XXX_Size() int {
	return xxx_messageInfo_GetPrimitivesResponse.Size(m)
}
func (m *GetPrimitivesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPrimitivesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPrimitivesResponse proto.InternalMessageInfo

func (m *GetPrimitivesResponse) GetInfo() []*PrimitiveInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterType((*PrimitiveInfo)(nil), "atomix.primitives.PrimitiveInfo")
	proto.RegisterType((*GetPrimitivesRequest)(nil), "atomix.primitives.GetPrimitivesRequest")
	proto.RegisterType((*GetPrimitivesResponse)(nil), "atomix.primitives.GetPrimitivesResponse")
}

func init() { proto.RegisterFile("primitives/primitives.proto", fileDescriptor_18b8a7b9552a23a1) }

var fileDescriptor_18b8a7b9552a23a1 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2e, 0x28, 0xca, 0xcc,
	0xcd, 0x2c, 0xc9, 0x2c, 0x4b, 0x2d, 0xd6, 0x47, 0x30, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85,
	0x04, 0x13, 0x4b, 0xf2, 0x73, 0x33, 0x2b, 0xf4, 0x10, 0x12, 0x52, 0xe2, 0x60, 0x99, 0xe4, 0xfc,
	0x1c, 0x7d, 0x18, 0x03, 0xa2, 0x56, 0xc9, 0x9c, 0x8b, 0x37, 0x00, 0xa6, 0xcc, 0x33, 0x2f, 0x2d,
	0x5f, 0x48, 0x88, 0x8b, 0x25, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08,
	0xcc, 0x06, 0x89, 0x95, 0x54, 0x16, 0xa4, 0x4a, 0x30, 0x41, 0xc4, 0x40, 0x6c, 0x25, 0x2d, 0x2e,
	0x11, 0xf7, 0xd4, 0x12, 0xb8, 0xde, 0xe2, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0xb8, 0x5a,
	0x46, 0x24, 0xb5, 0xbe, 0x5c, 0xa2, 0x68, 0x6a, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x4c,
	0xb8, 0x58, 0x32, 0xf3, 0xd2, 0xf2, 0x25, 0x18, 0x15, 0x98, 0x35, 0xb8, 0x8d, 0x14, 0xf4, 0x30,
	0x1c, 0xae, 0x87, 0xe2, 0xb8, 0x20, 0xb0, 0x6a, 0xa3, 0x4a, 0x2e, 0x41, 0x84, 0x59, 0xc1, 0xa9,
	0x45, 0x65, 0x99, 0xc9, 0xa9, 0x42, 0x29, 0x5c, 0xbc, 0x28, 0x76, 0x08, 0xa9, 0x63, 0x31, 0x0d,
	0x9b, 0x8b, 0xa5, 0x34, 0x08, 0x2b, 0x84, 0x38, 0x57, 0x89, 0xc1, 0x49, 0x96, 0x4b, 0x32, 0x33,
	0x1f, 0xa6, 0x3e, 0xbd, 0xa8, 0x20, 0x19, 0x49, 0x53, 0x00, 0x63, 0x12, 0x1b, 0x38, 0x50, 0x8d,
	0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xbd, 0xe7, 0x02, 0x36, 0x9f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PrimitivesServiceClient is the client API for PrimitivesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PrimitivesServiceClient interface {
	GetPrimitives(ctx context.Context, in *GetPrimitivesRequest, opts ...grpc.CallOption) (*GetPrimitivesResponse, error)
}

type primitivesServiceClient struct {
	cc *grpc.ClientConn
}

func NewPrimitivesServiceClient(cc *grpc.ClientConn) PrimitivesServiceClient {
	return &primitivesServiceClient{cc}
}

func (c *primitivesServiceClient) GetPrimitives(ctx context.Context, in *GetPrimitivesRequest, opts ...grpc.CallOption) (*GetPrimitivesResponse, error) {
	out := new(GetPrimitivesResponse)
	err := c.cc.Invoke(ctx, "/atomix.primitives.PrimitivesService/GetPrimitives", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrimitivesServiceServer is the server API for PrimitivesService service.
type PrimitivesServiceServer interface {
	GetPrimitives(context.Context, *GetPrimitivesRequest) (*GetPrimitivesResponse, error)
}

// UnimplementedPrimitivesServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPrimitivesServiceServer struct {
}

func (*UnimplementedPrimitivesServiceServer) GetPrimitives(ctx context.Context, req *GetPrimitivesRequest) (*GetPrimitivesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrimitives not implemented")
}

func RegisterPrimitivesServiceServer(s *grpc.Server, srv PrimitivesServiceServer) {
	s.RegisterService(&_PrimitivesService_serviceDesc, srv)
}

func _PrimitivesService_GetPrimitives_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPrimitivesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrimitivesServiceServer).GetPrimitives(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/atomix.primitives.PrimitivesService/GetPrimitives",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrimitivesServiceServer).GetPrimitives(ctx, req.(*GetPrimitivesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PrimitivesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "atomix.primitives.PrimitivesService",
	HandlerType: (*PrimitivesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPrimitives",
			Handler:    _PrimitivesService_GetPrimitives_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "primitives/primitives.proto",
}
